#!/bin/bash
# generated by chatGPT

img_find_duplicates() {
    declare -A file_map
    for file in *; do
        # get the file name without extension
        file_name=${file%.*}
        if [[ ${file_map[$file_name]} ]]; then
            echo "$file"
        else
            file_map[$file_name]=1
        fi
    done
}
